[package]
name = "nus3audio"
version = "1.1.0"
authors = ["jam1garner <jam1.mcleod@hotmail.com>"]
edition = "2018"

[dependencies]
itertools = "0.8"
nom = "4"
clap = "2"
byteorder = "1.3"
crc = "^1.0.0"
