name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          target: x86_64-pc-windows-gnu
          override: true
    - name: Add Windows
      run:
        rustup target add x86_64-pc-windows-gnu
    - name: Build Linux
      run:
        cargo build --release --target x86_64-unknown-linux-gnu
    - name: Build Windows
      run:
        cargo build --release --target x86_64-pc-windows-gnu
       
