name: Rust

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - id: component
      uses: actions-rs/components-nightly@v1
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: ${{ steps.component.outputs.toolchain }}
          override: true
    - name: Build
      run:
        rustup target add x86_64-pc-windows-gnu
        cargo build --release --target x86_64-unknown-linux-gnu
        cargo build --release --target x86_64-pc-windows-gnu
        cargo build --release --target x86_64-apple-darwin
